export enum notionBlockNamesDoc {
  BOOKMARK = "bookmark", // not implemented
  BREADCRUMB = "breadcrumb", // not implemented
  BULLETED_LIST_ITEM = "bulleted_list_item",
  CALLOUT = "callout",
  CHILD_DATABASE = "child_database", // not implemented
  CHILD_PAGE = "child_page", // not implemented
  CODE = "code",
  COLUMN = "column", // not implemented
  COLUMN_LIST = "column_list", // not implemented
  DIVIDER = "divider",
  EMBED = "embed", // not implemented
  EQUATION = "equation", // not implemented
  FILE = "file", // not implemented
  HEADING_1 = "heading_1",
  HEADING_2 = "heading_2",
  HEADING_3 = "heading_3",
  IMAGE = "image",
  LINK_PREVIEW = "link_preview", // not implemented
  LINK_TO_PAGE = "link_to_page", // not implemented
  NUMBERED_LIST_ITEM = "numbered_list_item",
  PARAGRAPH = "paragraph",
  PDF = "pdf", // not implemented
  QUOTE = "quote",
  SYNCED_BLOCK = "synced_block", // not implemented
  TABLE = "table", // not implemented
  TABLE_OF_CONTENTS = "table_of_contents", // not implemented
  TABLE_ROW = "table_row", // not implemented
  TEMPLATE = "template", // not implemented
  TO_DO = "to_do",
  TOGGLE = "toggle",
  UNSUPPORTED = "unsupported",
  VIDEO = "video", // not implemented
}
