export enum colorType {
  BLUE = "blue",
  BLUE_BG = "blue_background",
  BROWN = "brown",
  BROWN_BG = "brown_background",
  DEFAULT = "default",
  GRAY = "gray",
  GRAY_BG = "gray_background",
  GREEN = "green",
  GREEN_BG = "green_background",
  ORANGE = "orange",
  ORANGE_BG = "orange_background",
  YELLOW = "yellow",
  YELLOW_BG = "yellow_background",
  PINK = "pink",
  PINK_BG = "pink_background",
  PURPLE = "purple",
  PURPLE_BG = "purple_background",
  RED = "red",
  RED_BG = "red_background",
}
